app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin

from . import db
from . import login_manager


CURRENCIES = "CZK", "EUR"

class Offer(db.Model):
    __tablename__ = 'offers'
    id = db.Column(db.Integer, primary_key=True)
    currency_from = db.Column(db.Enum(*CURRENCIES))
    currency_to = db.Column(db.Enum(*CURRENCIES))
    amount = db.Column(db.Integer)
    expires = db.Column(db.DateTime)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    offers = db.relationship('Offer', backref='owner')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms.fields.html5 import (IntegerField,
                                  DateField)
from wtforms import SelectField, FloatField

from ..models import Offer, CURRENCIES

CURRENCIES = [(c, c) for c in CURRENCIES]

class OfferForm(Form):
    currency_from = SelectField('From currency', choices=CURRENCIES)
    currency_to = SelectField('To currency', choices=CURRENCIES)
    amount = IntegerField('Amount')
    expires = DateField('Expiration date')
    latitude = FloatField('Latitude', default=49.22573)
    longitude = FloatField('Longitude', default=16.58205)

app/__init__.py
from flask import Flask, render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.googlemaps import GoogleMaps
from flask.ext.login import LoginManager
from flask.ext.moment import Moment

from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
googlemaps = GoogleMaps()
moment = Moment()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    googlemaps.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from datetime import datetime

from flask.ext.googlemaps import Map
from flask.ext.login import login_required, current_user

from flask import render_template, redirect
from . import main
from .forms import OfferForm
from ..models import Offer
from .. import db

@main.route('/')
def index():
    offers = Offer.query.all()
    markers = [(o.latitude, o.longitude) for o in offers]

    gmap = Map(identifier="view-side",
               lat=49.22573,
               lng=16.58205,
               markers=markers,
               style="height:600px;width:100%;")
    return render_template("index.html", gmap=gmap, markers=markers, offers=offers)

@main.route('/new', methods=['GET', 'POST'])
@login_required
def new_offer():
    form = OfferForm()
    if form.validate_on_submit():
        offer = Offer(currency_from=form.currency_from.data,
                      currency_to=form.currency_to.data,
                      amount=form.amount.data,
                      expires=datetime.now(),
                      latitude=form.latitude.data,
                      longitude=form.longitude.data,
                      owner_id=current_user.id)
        db.session.add(offer)
        return redirect('/')
    return render_template('new_offer.html', form=form)

@main.route('/propose/<offer_id>', methods=['GET', 'POST'])
@login_required
def propose_offer(offer_id):
    form = OfferForm()
    my_offers = current_user.offers
    return render_template('propose_offer.html', my_offers=my_offers, form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}xchng{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">XCHNG</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/new">New Offer</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}"> Sign Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}"> Sign In</a></li>
                {% endif %}
                <li><a href="/new">New Offer</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}xchng{% endblock %}

{% block head %}
{{ super() }}
{{ gmap.js }}
{% endblock %}

{% block content %}
<div class="col-md-8">
{{ gmap.html }}
</div>
<div class="col-md-4">
  <table class="table table-hover">
    <thead>
      <th>From</th>
      <th>To</th>
      <th>Amount</th>
      <th>Expires in</th>
      <th></th>
    </thead>
    <tbody>
    {% for offer in offers %}
      <tr>
        <td>{{ offer.currency_from }}</td>
        <td>{{ offer.currency_to }}</td>
        <td>{{ offer.amount }}</td>
        <td>{{ moment(offer.expires).fromNow() }}</td>
        <td>
            <a href="{{ url_for('main.propose_offer', offer_id=offer.id) }}">accept offer</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
{% if result.error %}
<h2>Error: {{ result.error.message }}</h2>
{% endif %}
{% if result.user %}
{{ result.user.name }}
{% endif %}

app/templates/new_offer.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}xchng - New Offer{% endblock %}

{% block content %}
<form class="col-md-5" method="POST" action="/new">
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.currency_from) }}
    {{ wtf.form_field(form.currency_to) }}
    {{ wtf.form_field(form.amount) }}
    {{ wtf.form_field(form.expires) }}
    {{ wtf.form_field(form.latitude) }}
    {{ wtf.form_field(form.longitude) }}
    <input class="btn btn-default" type="submit" value="Submit">
</form>
{% endblock %}